name: neo
description: DFS neo - The new are of stock trading
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.2.0+3

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_hooks: ^0.18.4
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  amazon_cognito_identity_dart_2: ^2.1.2
  shared_preferences: ^2.0.15
  flutter_launcher_icons: ^0.9.3
  flutter_native_splash: ^2.2.3
  fl_chart: ^0.51.0
  dio: ^4.0.6
  rxdart: ^0.27.4
  shimmer: ^2.0.0
  google_fonts: ^3.0.1
  get_it: ^7.2.0
  mockito: ^5.2.0
  is_first_run: ^1.0.0
  url_launcher: ^6.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.1.11

flutter_icons:
  android: "launcher_icon"
  adaptive_icon_background: "#FFFFFF"
  ios: true
  image_path: "assets/dfsicon.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/dfssplash.png"


flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/
    - assets/images/

