const double AUTH_NEWPW_CONTAINTER_HEIGHT = 420;
const double AUTH_VERIFYACC_CONTAINTER_HEIGHT = 310;
const double AUTH_LOGIN_CONTAINTER_HEIGHT = 400;
const double AUTH_REGISTER_CONTAINTER_HEIGHT = 440;
