# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Build and upload the current version to testflight"
  lane :test_flight do
    sync_code_signing(type: "appstore", readonly: true, app_identifier: "com.dfsswiss.neo")
    build_app(scheme: "Runner")
    upload_to_testflight(api_key_path: "api_key.json")
    # add actions here: https://docs.fastlane.tools/actions
  end
end
