// Mocks generated by Mockito 5.2.0 from annotations
// in neo/test/helpers/test_helpers.dart.
// Do not manually edit this file.

import 'dart:async' as _i8;
import 'dart:ui' as _i13;

import 'package:amazon_cognito_identity_dart_2/cognito.dart' as _i18;
import 'package:amplitude_flutter/amplitude.dart' as _i6;
import 'package:bugsnag_flutter/bugsnag_flutter.dart' as _i22;
import 'package:dio/dio.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:neo/enums/app_state.dart' as _i20;
import 'package:neo/enums/data_source.dart' as _i15;
import 'package:neo/models/stockdata_datapoint.dart' as _i9;
import 'package:neo/models/stockdatadocument.dart' as _i4;
import 'package:neo/models/user_balance_datapoint.dart' as _i5;
import 'package:neo/models/user_model.dart' as _i3;
import 'package:neo/models/userasset_datapoint.dart' as _i12;
import 'package:neo/services/analytics_service.dart' as _i16;
import 'package:neo/services/app_state_service.dart' as _i19;
import 'package:neo/services/cognito_service.dart' as _i17;
import 'package:neo/services/crashlytics_service.dart' as _i21;
import 'package:neo/services/data_service.dart' as _i14;
import 'package:neo/services/rest_service.dart' as _i7;
import 'package:neo/types/api/stockdata_bulk_fetch_request.dart' as _i11;
import 'package:neo/types/stockdata_interval_enum.dart' as _i10;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeDio_0 extends _i1.Fake implements _i2.Dio {}

class _FakeUserModel_1 extends _i1.Fake implements _i3.UserModel {}

class _FakeStockdataDocument_2 extends _i1.Fake
    implements _i4.StockdataDocument {}

class _FakeUserBalanceDatapoint_3 extends _i1.Fake
    implements _i5.UserBalanceDatapoint {}

class _FakeAmplitude_4 extends _i1.Fake implements _i6.Amplitude {}

/// A class which mocks [RESTService].
///
/// See the documentation for Mockito's code generation for more information.
class MockRESTService extends _i1.Mock implements _i7.RESTService {
  MockRESTService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Dio get dio =>
      (super.noSuchMethod(Invocation.getter(#dio), returnValue: _FakeDio_0())
          as _i2.Dio);
  @override
  set dio(_i2.Dio? _dio) => super.noSuchMethod(Invocation.setter(#dio, _dio),
      returnValueForMissingStub: null);
  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);
  @override
  _i8.Future<List<_i9.StockdataDatapoint>> getStockdata(
          String? symbol, _i10.StockdataInterval? interval,
          {int? retryCount = 0}) =>
      (super.noSuchMethod(
              Invocation.method(
                  #getStockdata, [symbol, interval], {#retryCount: retryCount}),
              returnValue: Future<List<_i9.StockdataDatapoint>>.value(
                  <_i9.StockdataDatapoint>[]))
          as _i8.Future<List<_i9.StockdataDatapoint>>);
  @override
  _i8.Future<Map<String, Map<_i10.StockdataInterval, List<_i9.StockdataDatapoint>>>> getStockdataBulk(
          _i11.StockdataBulkFetchRequest? request,
          {int? retryCount = 0}) =>
      (super.noSuchMethod(
          Invocation.method(
              #getStockdataBulk, [request], {#retryCount: retryCount}),
          returnValue: Future<Map<String, Map<_i10.StockdataInterval, List<_i9.StockdataDatapoint>>>>.value(
              <String, Map<_i10.StockdataInterval, List<_i9.StockdataDatapoint>>>{})) as _i8
          .Future<Map<String, Map<_i10.StockdataInterval, List<_i9.StockdataDatapoint>>>>);
  @override
  _i8.Future<_i3.UserModel> getUserData({int? retryCount = 0}) =>
      (super.noSuchMethod(
              Invocation.method(#getUserData, [], {#retryCount: retryCount}),
              returnValue: Future<_i3.UserModel>.value(_FakeUserModel_1()))
          as _i8.Future<_i3.UserModel>);
  @override
  _i8.Future<_i4.StockdataDocument> getStockInfo(String? symbol,
          {int? retryCount = 0}) =>
      (super.noSuchMethod(
          Invocation.method(#getStockInfo, [symbol], {#retryCount: retryCount}),
          returnValue: Future<_i4.StockdataDocument>.value(
              _FakeStockdataDocument_2())) as _i8
          .Future<_i4.StockdataDocument>);
  @override
  _i8.Future<List<_i4.StockdataDocument>> getStockInfoBulk(
          List<String>? symbols,
          {int? retryCount = 0}) =>
      (super.noSuchMethod(
              Invocation.method(
                  #getStockInfoBulk, [symbols], {#retryCount: retryCount}),
              returnValue: Future<List<_i4.StockdataDocument>>.value(
                  <_i4.StockdataDocument>[]))
          as _i8.Future<List<_i4.StockdataDocument>>);
  @override
  _i8.Future<bool> addBalance(String? amount) =>
      (super.noSuchMethod(Invocation.method(#addBalance, [amount]),
          returnValue: Future<bool>.value(false)) as _i8.Future<bool>);
  @override
  _i8.Future<List<_i4.StockdataDocument>> getAvailiableStocks(
          {int? retryCount = 0}) =>
      (super.noSuchMethod(
              Invocation.method(
                  #getAvailiableStocks, [], {#retryCount: retryCount}),
              returnValue: Future<List<_i4.StockdataDocument>>.value(
                  <_i4.StockdataDocument>[]))
          as _i8.Future<List<_i4.StockdataDocument>>);
  @override
  _i8.Future<List<_i12.UserassetDatapoint>> getUserAssets(
          {int? retryCount = 0}) =>
      (super.noSuchMethod(
              Invocation.method(#getUserAssets, [], {#retryCount: retryCount}),
              returnValue: Future<List<_i12.UserassetDatapoint>>.value(
                  <_i12.UserassetDatapoint>[]))
          as _i8.Future<List<_i12.UserassetDatapoint>>);
  @override
  _i8.Future<List<_i12.UserassetDatapoint>> getUserAssetsHistory(
          {_i10.StockdataInterval? interval, int? retryCount = 0}) =>
      (super.noSuchMethod(
              Invocation.method(#getUserAssetsHistory, [],
                  {#interval: interval, #retryCount: retryCount}),
              returnValue: Future<List<_i12.UserassetDatapoint>>.value(
                  <_i12.UserassetDatapoint>[]))
          as _i8.Future<List<_i12.UserassetDatapoint>>);
  @override
  _i8.Future<List<_i5.UserBalanceDatapoint>> getUserBalanceHistory(
          {_i10.StockdataInterval? interval, int? retryCount = 0}) =>
      (super.noSuchMethod(
              Invocation.method(#getUserBalanceHistory, [],
                  {#interval: interval, #retryCount: retryCount}),
              returnValue: Future<List<_i5.UserBalanceDatapoint>>.value(
                  <_i5.UserBalanceDatapoint>[]))
          as _i8.Future<List<_i5.UserBalanceDatapoint>>);
  @override
  _i8.Future<_i5.UserBalanceDatapoint> getBalance({int? retryCount = 0}) =>
      (super.noSuchMethod(
              Invocation.method(#getBalance, [], {#retryCount: retryCount}),
              returnValue: Future<_i5.UserBalanceDatapoint>.value(
                  _FakeUserBalanceDatapoint_3()))
          as _i8.Future<_i5.UserBalanceDatapoint>);
  @override
  _i8.Future<List<_i12.UserassetDatapoint>> getAssetForSymbol(String? symbol,
          {int? retryCount = 0}) =>
      (super.noSuchMethod(
              Invocation.method(
                  #getAssetForSymbol, [symbol], {#retryCount: retryCount}),
              returnValue: Future<List<_i12.UserassetDatapoint>>.value(
                  <_i12.UserassetDatapoint>[]))
          as _i8.Future<List<_i12.UserassetDatapoint>>);
  @override
  _i8.Future<bool> buyAsset(String? symbol, double? amountInDollar) => (super
      .noSuchMethod(Invocation.method(#buyAsset, [symbol, amountInDollar]),
          returnValue: Future<bool>.value(false)) as _i8.Future<bool>);
  @override
  _i8.Future<bool> sellAsset(String? symbol, double? ammountOfTokensToSell) =>
      (super.noSuchMethod(
          Invocation.method(#sellAsset, [symbol, ammountOfTokensToSell]),
          returnValue: Future<bool>.value(false)) as _i8.Future<bool>);
  @override
  void addListener(_i13.VoidCallback? listener) =>
      super.noSuchMethod(Invocation.method(#addListener, [listener]),
          returnValueForMissingStub: null);
  @override
  void removeListener(_i13.VoidCallback? listener) =>
      super.noSuchMethod(Invocation.method(#removeListener, [listener]),
          returnValueForMissingStub: null);
  @override
  void dispose() => super.noSuchMethod(Invocation.method(#dispose, []),
      returnValueForMissingStub: null);
  @override
  void notifyListeners() =>
      super.noSuchMethod(Invocation.method(#notifyListeners, []),
          returnValueForMissingStub: null);
}

/// A class which mocks [DataService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDataService extends _i1.Mock implements _i14.DataService {
  MockDataService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);
  @override
  dynamic handleUserDataUpdate(String? message) =>
      super.noSuchMethod(Invocation.method(#handleUserDataUpdate, [message]));
  @override
  T? getDataFromCacheIfAvaliable<T>(String? key) => (super
          .noSuchMethod(Invocation.method(#getDataFromCacheIfAvaliable, [key]))
      as T?);
  @override
  _i8.Stream<_i3.UserModel> getUserData(
          {_i15.DataSource? source = _i15.DataSource.cache}) =>
      (super.noSuchMethod(
              Invocation.method(#getUserData, [], {#source: source}),
              returnValue: Stream<_i3.UserModel>.empty())
          as _i8.Stream<_i3.UserModel>);
  @override
  _i8.Stream<_i4.StockdataDocument> getStockInfo(String? symbol,
          {_i15.DataSource? source = _i15.DataSource.cache}) =>
      (super.noSuchMethod(
              Invocation.method(#getStockInfo, [symbol], {#source: source}),
              returnValue: Stream<_i4.StockdataDocument>.empty())
          as _i8.Stream<_i4.StockdataDocument>);
  @override
  _i8.Stream<List<_i4.StockdataDocument>> getAvailableStocks(
          {_i15.DataSource? source = _i15.DataSource.cache}) =>
      (super.noSuchMethod(
              Invocation.method(#getAvailableStocks, [], {#source: source}),
              returnValue: Stream<List<_i4.StockdataDocument>>.empty())
          as _i8.Stream<List<_i4.StockdataDocument>>);
  @override
  _i8.Stream<List<_i12.UserassetDatapoint>> getUserAssets(
          {_i15.DataSource? source = _i15.DataSource.cache}) =>
      (super.noSuchMethod(
              Invocation.method(#getUserAssets, [], {#source: source}),
              returnValue: Stream<List<_i12.UserassetDatapoint>>.empty())
          as _i8.Stream<List<_i12.UserassetDatapoint>>);
  @override
  _i8.Stream<List<_i12.UserassetDatapoint>> getUserAssetsHistory(
          {_i15.DataSource? source = _i15.DataSource.cache}) =>
      (super.noSuchMethod(
              Invocation.method(#getUserAssetsHistory, [], {#source: source}),
              returnValue: Stream<List<_i12.UserassetDatapoint>>.empty())
          as _i8.Stream<List<_i12.UserassetDatapoint>>);
  @override
  _i8.Stream<List<_i5.UserBalanceDatapoint>> getUserBalanceHistory(
          {_i15.DataSource? source = _i15.DataSource.cache}) =>
      (super.noSuchMethod(
              Invocation.method(#getUserBalanceHistory, [], {#source: source}),
              returnValue: Stream<List<_i5.UserBalanceDatapoint>>.empty())
          as _i8.Stream<List<_i5.UserBalanceDatapoint>>);
  @override
  _i8.Stream<_i5.UserBalanceDatapoint> getUserBalance(
          {_i15.DataSource? source = _i15.DataSource.cache}) =>
      (super.noSuchMethod(
              Invocation.method(#getUserBalance, [], {#source: source}),
              returnValue: Stream<_i5.UserBalanceDatapoint>.empty())
          as _i8.Stream<_i5.UserBalanceDatapoint>);
  @override
  _i8.Future<bool> buyAsset(String? symbol, double? amountInDollar) => (super
      .noSuchMethod(Invocation.method(#buyAsset, [symbol, amountInDollar]),
          returnValue: Future<bool>.value(false)) as _i8.Future<bool>);
  @override
  _i8.Future<bool> sellAsset(String? symbol, double? ammountOfTokensToSell) =>
      (super.noSuchMethod(
          Invocation.method(#sellAsset, [symbol, ammountOfTokensToSell]),
          returnValue: Future<bool>.value(false)) as _i8.Future<bool>);
  @override
  _i8.Future<bool> addUserBalance(String? amount) =>
      (super.noSuchMethod(Invocation.method(#addUserBalance, [amount]),
          returnValue: Future<bool>.value(false)) as _i8.Future<bool>);
  @override
  _i8.Stream<List<_i12.UserassetDatapoint>> getUserAssetsForSymbol(
          String? symbol) =>
      (super.noSuchMethod(Invocation.method(#getUserAssetsForSymbol, [symbol]),
              returnValue: Stream<List<_i12.UserassetDatapoint>>.empty())
          as _i8.Stream<List<_i12.UserassetDatapoint>>);
  @override
  void addListener(_i13.VoidCallback? listener) =>
      super.noSuchMethod(Invocation.method(#addListener, [listener]),
          returnValueForMissingStub: null);
  @override
  void removeListener(_i13.VoidCallback? listener) =>
      super.noSuchMethod(Invocation.method(#removeListener, [listener]),
          returnValueForMissingStub: null);
  @override
  void dispose() => super.noSuchMethod(Invocation.method(#dispose, []),
      returnValueForMissingStub: null);
  @override
  void notifyListeners() =>
      super.noSuchMethod(Invocation.method(#notifyListeners, []),
          returnValueForMissingStub: null);
}

/// A class which mocks [AnalyticsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAnalyticsService extends _i1.Mock implements _i16.AnalyticsService {
  MockAnalyticsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Amplitude get amplitude =>
      (super.noSuchMethod(Invocation.getter(#amplitude),
          returnValue: _FakeAmplitude_4()) as _i6.Amplitude);
  @override
  _i8.Future<void> init() => (super.noSuchMethod(Invocation.method(#init, []),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future<void>.value()) as _i8.Future<void>);
  @override
  _i8.Future<void> identifyUser({bool? forwardToCrashlytics = true}) =>
      (super.noSuchMethod(
          Invocation.method(
              #identifyUser, [], {#forwardToCrashlytics: forwardToCrashlytics}),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i8.Future<void>);
  @override
  _i8.Future<void> trackEvent(String? eventType,
          {Map<String, dynamic>? eventProperties,
          bool? outOfSession,
          bool? forwardToCrashlytics = true}) =>
      (super.noSuchMethod(
          Invocation.method(#trackEvent, [
            eventType
          ], {
            #eventProperties: eventProperties,
            #outOfSession: outOfSession,
            #forwardToCrashlytics: forwardToCrashlytics
          }),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i8.Future<void>);
}

/// A class which mocks [CognitoService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCognitoService extends _i1.Mock implements _i17.CognitoService {
  MockCognitoService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool isIdTokenExpired() =>
      (super.noSuchMethod(Invocation.method(#isIdTokenExpired, []),
          returnValue: false) as bool);
  @override
  bool isSessionPresent() =>
      (super.noSuchMethod(Invocation.method(#isSessionPresent, []),
          returnValue: false) as bool);
  @override
  dynamic createAndAuthenticateUser(String? username, String? password) =>
      super.noSuchMethod(
          Invocation.method(#createAndAuthenticateUser, [username, password]));
  @override
  dynamic confirmRegistration(String? code) =>
      super.noSuchMethod(Invocation.method(#confirmRegistration, [code]));
  @override
  bool isUserPresent() =>
      (super.noSuchMethod(Invocation.method(#isUserPresent, []),
          returnValue: false) as bool);
  @override
  dynamic sendNewPasswordRequired(String? newPassword) => super
      .noSuchMethod(Invocation.method(#sendNewPasswordRequired, [newPassword]));
  @override
  _i8.Future<_i18.CognitoUser?> getCurrentPoolUser() =>
      (super.noSuchMethod(Invocation.method(#getCurrentPoolUser, []),
              returnValue: Future<_i18.CognitoUser?>.value())
          as _i8.Future<_i18.CognitoUser?>);
  @override
  dynamic registerUser(String? userName, String? email, String? password) =>
      super.noSuchMethod(
          Invocation.method(#registerUser, [userName, email, password]));
  @override
  dynamic changePassword(String? oldPassword, String? newPassword) =>
      super.noSuchMethod(
          Invocation.method(#changePassword, [oldPassword, newPassword]));
  @override
  dynamic initForgotPassword(String? username) =>
      super.noSuchMethod(Invocation.method(#initForgotPassword, [username]));
  @override
  dynamic completeForgotPassword(String? code, String? newPassword) =>
      super.noSuchMethod(
          Invocation.method(#completeForgotPassword, [code, newPassword]));
}

/// A class which mocks [AppStateService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppStateService extends _i1.Mock implements _i19.AppStateService {
  MockAppStateService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i20.AppState get state => (super.noSuchMethod(Invocation.getter(#state),
      returnValue: _i20.AppState.signedOut) as _i20.AppState);
  @override
  set state(_i20.AppState? newState) =>
      super.noSuchMethod(Invocation.setter(#state, newState),
          returnValueForMissingStub: null);
  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);
  @override
  void addListener(_i13.VoidCallback? listener) =>
      super.noSuchMethod(Invocation.method(#addListener, [listener]),
          returnValueForMissingStub: null);
  @override
  void removeListener(_i13.VoidCallback? listener) =>
      super.noSuchMethod(Invocation.method(#removeListener, [listener]),
          returnValueForMissingStub: null);
  @override
  void dispose() => super.noSuchMethod(Invocation.method(#dispose, []),
      returnValueForMissingStub: null);
  @override
  void notifyListeners() =>
      super.noSuchMethod(Invocation.method(#notifyListeners, []),
          returnValueForMissingStub: null);
}

/// A class which mocks [CrashlyticsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCrashlyticsService extends _i1.Mock
    implements _i21.CrashlyticsService {
  MockCrashlyticsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void start({String? apiKey, _i8.FutureOr<void> Function()? runApp}) =>
      super.noSuchMethod(
          Invocation.method(#start, [], {#apiKey: apiKey, #runApp: runApp}),
          returnValueForMissingStub: null);
  @override
  _i8.Future<void> identifyUser() =>
      (super.noSuchMethod(Invocation.method(#identifyUser, []),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i8.Future<void>);
  @override
  _i8.Future<void> leaveBreadcrumb(String? eventType,
          {Map<String, Object>? eventProperties,
          _i22.BugsnagBreadcrumbType? type =
              _i22.BugsnagBreadcrumbType.manual}) =>
      (super.noSuchMethod(
          Invocation.method(#leaveBreadcrumb, [eventType],
              {#eventProperties: eventProperties, #type: type}),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i8.Future<void>);
}
