# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :staging do
    #gradle(
    #  tasks: ["clean", "bundle"],
    #  print_command: false,
    #  properties: {
    #    "android.injected.signing.store.file" => "keystore.jks",
    #    "android.injected.signing.store.password" => ENV['ANDROID_STORE_PASSWORD'],
    #    "android.injected.signing.key.alias" => ENV['ANDROID_KEY_ALIAS'],
    #    "android.injected.signing.key.password" => ENV['ANDROID_KEY_PASSWORD']
    #  }
    #)
    upload_to_play_store(
      track: "Staging", 
      version_code: flutter_version()["version_code"],
      skip_upload_screenshots: true,
      skip_upload_images: true,
      skip_upload_changelogs: true,
      json_key: "fastlane/google_key.json",
      aab: "build/app/outputs/bundle/release/app.aab"
    )
  end
end
